changelog:
  categories:
    - title: 🔥 Breaking Changes
      labels:
        - "type: breaking"

    - title: ⭐ New Features
      labels:
        - "type: feature"

    - title: 🐞 Bug Fixes
      labels:
        - "type: bug"

    - title: 🔨 Dependency Upgrades
      labels:
        - "type: dependency"

    - title: 📔 Documentation
      labels:
        - "type: documentation"

    - title: 🧹 Cleanup
      labels:
        - "type: polish"

    - title: ✔ Other Changes
      labels:
        - "*"
