name: Build Master

on:
  push:
    branches: ['master']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout sourcecode
        uses: actions/checkout@v2.4.0

      - name: Setup Java
        uses: actions/setup-java@v2.5.0
        with:
          distribution: liberica
          java-version: 11

      - name: Build
        run: mvn -B -ntp verify
